### ISSUE TITLE
Could not find matching function to call loaded from the SavedModel. 

### ISSUE THREAD

**Issue by Cdk29** [rstudio/tfhub#20]
I am following the tutorial here : https://tensorflow.rstudio.com/guide/tfhub/intro/

At :

```
library(tfhub)
library(keras)

input <- layer_input(shape = c(32, 32, 3))

output <- input %>%
  # we are using a pre-trained MobileNet model!
  layer_hub(handle = "https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/2") %>%
  layer_dense(units = 10, activation = "softmax")
```

I got : 

> Error in py_call_impl(callable, dots$args, dots$keywords): ValueError: in converted code:
>     relative to /usr/local/share/.virtualenvs/r-reticulate/lib/python3.7/site-packages:
> 
>     tensorflow_hub/keras_layer.py:216 call  *
>         result = smart_cond.smart_cond(training,
>     tensorflow_core/python/framework/smart_cond.py:56 smart_cond
>         return false_fn()
>     tensorflow_core/python/saved_model/load.py:436 _call_attribute
>         return instance.__call__(*args, **kwargs)
>     tensorflow_core/python/eager/def_function.py:457 __call__
>         result = self._call(*args, **kwds)
>     tensorflow_core/python/eager/def_function.py:494 _call
>         results = self._stateful_fn(*args, **kwds)
>     tensorflow_core/python/eager/function.py:1822 __call__
>         graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
>     tensorflow_core/python/eager/function.py:2150 _maybe_define_function
>         graph_function = self._create_graph_function(args, kwargs)
>     tensorflow_core/python/eager/function.py:2041 _create_graph_function
>         capture_by_value=self._capture_by_value),
>     tensorflow_core/python/framework/func_graph.py:915 func_graph_from_py_func
>         func_outputs = python_func(*func_args, **func_kwargs)
>     tensorflow_core/python/eager/def_function.py:358 wrapped_fn
>         return weak_wrapped_fn().__wrapped__(*args, **kwds)
>     tensorflow_core/python/saved_model/function_deserialization.py:262 restored_function_body
>         "\n\n".join(signature_descriptions)))
> 
>     ValueError: Could not find matching function to call loaded from the SavedModel. Got:
>       Positional arguments (3 total):
>         * Tensor("inputs:0", shape=(None, 32, 32, 3), dtype=float32)
>         * False
>         * 0.99
>       Keyword arguments: {}
>     
>     Expected these arguments to match one of the following 2 option(s):
>     
>     Option 1:
>       Positional arguments (3 total):
>         * TensorSpec(shape=(None, 224, 224, 3), dtype=tf.float32, name='inputs')
>         * True
>         * TensorSpec(shape=(), dtype=tf.float32, name='batch_norm_momentum')
>       Keyword arguments: {}
>     
>     Option 2:
>       Positional arguments (3 total):
>         * TensorSpec(shape=(None, 224, 224, 3), dtype=tf.float32, name='inputs')
>         * False
>         * TensorSpec(shape=(), dtype=tf.float32, name='batch_norm_momentum')
>       Keyword arguments: {}
> 
> 
> Detailed traceback: 
>   File "/usr/local/share/.virtualenvs/r-reticulate/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 842, in __call__
>     outputs = call_fn(cast_inputs, *args, **kwargs)
>   File "/usr/local/share/.virtualenvs/r-reticulate/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
>     raise e.ag_error_metadata.to_exception(e)
> 
> Traceback:
> 
> 1. input %>% layer_hub(handle = "https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/2") %>% 
>  .     layer_dense(units = 10, activation = "softmax")
> 2. withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
> 3. eval(quote(`_fseq`(`_lhs`)), env, env)
> 4. eval(quote(`_fseq`(`_lhs`)), env, env)
> 5. `_fseq`(`_lhs`)
> 6. freduce(value, `_function_list`)
> 7. function_list[[i]](value)
> 8. layer_hub(., handle = "https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/2")
> 9. keras::create_layer(tfhub$KerasLayer, object, append(list(handle = handle, 
>  .     trainable = trainable, arguments = arguments), args))
> 10. compose_layer(object, layer)
> 11. compose_layer.python.builtin.object(object, layer)
> 12. layer(object, ...)
> 13. py_call_impl(callable, dots$args, dots$keywords)

While it could be simply a problem inside of the environment of keras, because of : 

>     ValueError: Could not find matching function to call loaded from the SavedModel. Got:
>       Positional arguments (3 total):
>         * Tensor("inputs:0", shape=(None, 32, 32, 3), dtype=float32)
>         * False
>         * 0.99
>       Keyword arguments: {}
>     
>     Expected these arguments to match one of the following 2 option(s):
>     
>     Option 1:
>       Positional arguments (3 total):
>         * TensorSpec(shape=(None, 224, 224, 3), dtype=tf.float32, name='inputs')
>         * True
>         * TensorSpec(shape=(), dtype=tf.float32, name='batch_norm_momentum')
>       Keyword arguments: {}
>     
>     Option 2:
>       Positional arguments (3 total):
>         * TensorSpec(shape=(None, 224, 224, 3), dtype=tf.float32, name='inputs')
>         * False
>         * TensorSpec(shape=(), dtype=tf.float32, name='batch_norm_momentum')
>       Keyword arguments: {}

I wonder if the example/tutorial is still up to date and if the underlying library in Python did not changed.

**Comment by dfalbel** [comment]
Yes, looks like something has changed with recent versions of tfhub.

You can do:

```
output <- input %>%
  # we are using a pre-trained MobileNet model!
  layer_lambda(function(x) tensorflow::tf$image$resize(x, c(224L, 224L))) %>% 
  layer_hub(handle = "https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/4") %>%
  layer_dense(units = 10, activation = "softmax")
```

**Comment by Cdk29** [comment]
`input <- layer_input(shape = c(32, 32, 3))` 
or

`input <- layer_input(shape = c(224, 224, 3))`

`output <- input %>%
  layer_lambda(function(x) tensorflow::tf$image$resize(x, c(224L, 224L))) %>% 
  layer_hub(handle = "https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/4") %>%
  layer_dense(units = 10, activation = "softmax")`

Gave me : 

> Error in py_call_impl(callable, dots$args, dots$keywords): TypeError: in converted code:
> 
>     /usr/local/share/.virtualenvs/r-reticulate/lib/python3.7/site-packages/tensorflow_hub/keras_layer.py:232 call  *
>         result = self._apply_output_shape_if_set(inputs, result)
> 
>     TypeError: tf___apply_output_shape_if_set() takes 1 positional argument but 3 were given

**Comment by dfalbel** [comment]
Sorry, I can't reproduce it.

Can you run:

```
library(keras)
library(tfhub)

input <- layer_input(shape = c(32, 32, 3))

hub_layer <- layer_hub(handle = "https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/4")

output <- input %>%
  # we are using a pre-trained MobileNet model!
  layer_lambda(function(x) tensorflow::tf$image$resize(x, c(224L, 224L))) %>% 
  hub_layer %>%
  layer_dense(units = 10, activation = "softmax")
```

Also what's your:

```
tensorflow::tf_version()
tfhub:::tfhub$version$`__version__`
```

**Comment by Cdk29** [comment]
This time it worked !
Probably I made a mistake the first time.

‘2.0’
'0.7.0' for the output, respectively.

Thanks for the quick reply. Could you explained to me briefly why the 
`layer_lambda(function(x) tensorflow::tf$image$resize(x, c(224L, 224L)))`
?

**Comment by dfalbel** [comment]
Ah great! glad it worked. I will update the docs.

At some point the MobileNet hub model would automatically resize the images to match the input size of the images they used to train the model. Now, they are requiring the input to be the same size as the the images they used to train the model which is 224 x 224, so we use the `tf$image$resize` function to resize the images to the required size. 

We then use the layer_lambda just because we need to wrap the function call into a keras layer.

**Comment by Cdk29** [comment]
The error is back. I created a kernel on kaggle to do the tests [here](https://www.kaggle.com/cdk292/test-tf2/). The version of tfhub is now 0.8.0, (previous successful attempt was made with 0.7.0).

**Comment by Cdk29** [comment]
Okay I got it. Yesterday I was in interactive session, so I did not run everything from A to Z. It took me a bit of time to find what created the error, and turned out that running : 
`tfhub::install_tfhub()`
Provoked the downstream error.
